name: mrsheaf
description: MrSheaf App
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  segmented_button_slide: ^1.0.2
  easy_stepper: ^0.8.5
  awesome_bottom_bar: ^1.2.4
  http: ^1.1.0
  dio: ^5.3.2
  intl: ^0.19.0
  url_launcher: ^6.2.4
  file_picker: ^8.0.0+1
  image_picker: ^1.0.7
  crop_your_image: ^2.0.0
  permission_handler: ^11.3.1
  path: ^1.8.3
  cached_network_image: ^3.3.1
  google_maps_flutter: ^2.13.1
  google_maps_flutter_android: ^2.14.7
  google_maps_flutter_platform_interface: ^2.9.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_dotenv: ^5.2.1
  firebase_core:
  cloud_firestore:
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
    - family: Givonic
      fonts:
        - asset: assets/fonts/Givonic-Regular.ttf
        - asset: assets/fonts/Givonic-Bold.ttf
          weight: 700
        - asset: assets/fonts/Givonic-ExtraBold.ttf
          weight: 800
